project_id = "beybdwxmocwaeuizghnf"

[functions.create-user]
verify_jwt = true

[functions.upload-json]
verify_jwt = false

[functions.get-insights]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.get-analytics-v2]
verify_jwt = false
